### ISSUE TITLE
 the menu of run nodejs makes no effect in SublimeText-Nodejs v2.0.3, in win7 x64 sublime text v3.2.2

### ISSUE THREAD

**Issue by juejian** [tanepiper/SublimeText-Nodejs#102]
test environment describes as title.

after configuring node path and npm path  in `Nodejs.sublime-settings` , moreover update `Nodejs.sublime-build`.

when using default settings, ` tools -> NodeJS`, show:

![image](https://user-images.githubusercontent.com/12257223/68103306-2910bb00-ff11-11e9-9c01-7aba72389a12.png)

**the menu of  "run、run argument 、debug、debug argument etc" can't run, those are gray color. and relatived quick key can't use either.**

**but `ctrl + b` build can run.** result:

![image](https://user-images.githubusercontent.com/12257223/68103973-06cc6c80-ff14-11e9-91b2-c7fedce4cef7.png)

special config file content as below:

**Nodejs.sublime-settings:**

![image](https://user-images.githubusercontent.com/12257223/68103766-1d25f880-ff13-11e9-868a-0453f8042f7b.png)

**Nodejs.sublime-build**

![image](https://user-images.githubusercontent.com/12257223/68103868-71c97380-ff13-11e9-8162-9c554711e361.png)

test.js content:

``` javascript
var http = require('http');
http.createServer(function (request, response) {
  response.writeHead(200, {'Content-Type': 'text/plain'});
  response.end('Hello World\n');
}).listen(3000);
console.log('Server running at http://localhost:3000/');
```

How can I fix it?

If you have time, please reply me, thank you。

**Comment by varp** [comment]
But, the menu items only will be active on JavaScript file types. To set it on arbitrary files you can open Command Palette and type `Set Syntax JavaScript` and hit the Enter.

**Comment by juejian** [comment]
Thank you for your reply. but I have tried several methods,the question is still existed. 
now I only use ctrl + b(build) to run but can‘t debug with sublimeText3-nodejs.
