### ISSUE TITLE
NODE_PATH not being considered

### ISSUE THREAD

**Issue by zanona** [tanepiper/SublimeText-Nodejs#34]
I have `NODE_PATH` defined as

``` bash
export NODE_PATH="/Users/usename/Dropbox/Mackup/lib/node_modules"
```

where

``` bash
node
> require('request')
```

works fine on Terminal,
but when it comes to SublimeText-Nodejs it won't load any module I have installed, looking only for modules installed where the document is saved.

How can I use global NPM modules?

Thanks in advance

**Comment by varp** [comment]
Yep. Thanks @zanona
