### ISSUE TITLE
code completion across files

### ISSUE THREAD

**Issue by spruce** [tanepiper/SublimeText-Nodejs#41]
Hey,
I have the question whether it is possible to get all the methods put into the module.export by modules you required

Like:
You are editing file a which requires fileb like 
`var saver = require('fileb');`
in fileb you defined something like 
`module.export.save = function(item){ ... stuff; ...}`
and then you could say `saver.` and there apears the autocompletion for the save function

**Comment by varp** [comment]
For the autocompleting across files, you could install All Autocomplete package from the package manager.
The plugin offers you a pre-generated autocompletion for Nodejs and its std library, it doesn't offer you smart completion (evaluating a code in the context of your project files) as doing some IDEs.
