### ISSUE TITLE
Autocompletion duplicates root object

### ISSUE THREAD

**Issue by craignied** [tanepiper/SublimeText-Nodejs#61]
If I start to type an object and method in JS, say

<img width="402" alt="screen shot 2017-03-30 at 2 39 05 pm" src="https://cloud.githubusercontent.com/assets/1330498/24523244/0613a8f6-1558-11e7-977c-78e8b97fc644.png">

and then hit tab, the root object is duplicated in the autocomplete, eg.

`http.http.createServer(requestListener);`

**Comment by varp** [comment]
@craignied Will work on this in the next couple days

**Comment by varp** [comment]
@craignied please check out the new branch issue-61. It should solve the problem.

**Comment by varp** [comment]
Fixed in a new release v1.5.5. Check out the master branch or install the new version from package manager.
