### ISSUE TITLE
Turning off shortcuts

### ISSUE THREAD

**Issue by NolanChan** [tanepiper/SublimeText-Nodejs#62]
Hi, 

Could I ask how I can turn off shortcuts, specifically NodeJS > Debug [^ + D]? The NodeJS shortcuts are interfering with VI mode for me

Thanks!
Nolan

<img width="598" alt="screen shot 2017-05-05 at 12 45 09 pm" src="https://cloud.githubusercontent.com/assets/1487616/25761743/c24c5cd0-3190-11e7-9cc2-9732ac19cc03.png">

**Comment by varp** [comment]
Hi @NolanChan ,

I've added new functionality for changing default key bindings. Could you check out the branch issue-62?

**Comment by varp** [comment]
Fixed in a new release v1.5.5. Check out the master branch or install the new version from package manager.

**Comment by NolanChan** [comment]
Thanks @varp , will do
