### ISSUE TITLE
Certain completions not appearing

### ISSUE THREAD

**Issue by rkpatel33** [tanepiper/SublimeText-Nodejs#69]
Certain completions do not show up in the popup box, in particular, `console.log` from the `Nodejs.sublime-completions` file. Not sure what could be interfering with it, any suggestions on tracking it down? Seems most of the other ones do complete based on a random sampling of them.

![image](https://user-images.githubusercontent.com/3799489/29188049-b407d7c6-7dc6-11e7-8c4a-d3875c0c216c.png)

File name is `requests-test.js` and Sublime syntax is `JavaScript Next`.

```
{
  "trigger": "console.log();",
  "contents": "log();$0"
},
```

**Comment by varp** [comment]
Accepted. Thx 😊

**Comment by varp** [comment]
@rkpatel33 I'm planning to do grand refactor of the code. Be patient, please.

**Comment by rkpatel33** [comment]
Ok cool. Thanks for letting me know.

**Comment by varp** [comment]
@rkpatel33  Did you install JavaScript Next syntax from a package? Could you give a link to it?

**Comment by rkpatel33** [comment]
Yes I have that installed. I'm not sure what you meant by giving a link to it, do you want to path to it on my local machine?

**Comment by varp** [comment]
No, I don't  need a path on your local machine. If you installed it by PackageControl, could you find it on the [packagecontrol.io](https://packagecontrol.io) and give me a link to it? I can guess that you've installed that one - [JavaScript Next](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax)? But that package has a MISSING status... No one can install it anymore!

**Comment by rkpatel33** [comment]
Oh wow. Ok I'll try to get it to you later. But FYI I just switched over to VS Code today and it's like a dream for node development. I commited a couple hours to getting up on it and I think I'm off sublime text for good :)

**Comment by varp** [comment]
Resolved in the refactor branch
