### ISSUE TITLE
Problem with auto completion

### ISSUE THREAD

**Issue by jacobsun** [tanepiper/SublimeText-Nodejs#73]
The 'auto completion' is not 'to complete', but to replace. If I type 'fs', then the suggestion is 'fs.close()', I hit tab(or any other key I set), the result will be 'close()', not 'fs.close()'. 

sublime version: v3 3143 (x64)

And it makes `Javascript completion` plugin can not  auto-complete,  I am not sure whether this is nodejs's problem or  that plugin's.

**Comment by varp** [comment]
Could you try install last version of the plugin from the refactor branch ?

**Comment by wangxi761** [comment]
i have the same problem

**Comment by jacobsun** [comment]
@varp Yeah, the problem fixed. Thanks.
