### ISSUE TITLE
How to setup path when node is installed globally

### ISSUE THREAD

**Issue by maibin** [tanepiper/SublimeText-Nodejs#83]
Please refer to my question in here:
https://stackoverflow.com/questions/48141374/how-to-configure-nodejs-build-plugin-inside-sublime-text-3

I think it would be beneficial if you can show example how to specify the path to node in your plugin, as I can't configure it.

**Comment by varp** [comment]
I left a comment on StackOverflow. If it resolve your issue, please close the issue
