### ISSUE TITLE
Node path

### ISSUE THREAD

**Issue by NikhilDoWhile** [tanepiper/SublimeText-Nodejs#91]
<img width="952" alt="node" src="https://user-images.githubusercontent.com/9911561/39410587-1fa7d5f6-4c18-11e8-92e0-4f4bb19b202b.PNG">

Where to add node path (win-10 ) in sublime package setting.

**Comment by varp** [comment]
Hey,
If I understood your question right, on the right pane. But according to [the current documentation of the NodeJs](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders), you should correct the value instead of simply set it to `true`

**Comment by bennierja** [comment]
Hey varp,
Thanks for this package and in advance for your help. I also don't know what value "node_path" is supposed to be set to, or how to find that value. Thanks.
